# Generated by Django 5.2.6 on 2025-10-06 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_post_image_post_featured_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
