# Generated by Django 5.2.6 on 2025-10-06 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_comment_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
